"""fix frined relationship

Revision ID: 01279763056b
Revises: 65175d5b5fa2
Create Date: 2024-09-15 17:59:15.954394

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "01279763056b"
down_revision: str | None = "65175d5b5fa2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("friend")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friend",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("friend_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["friend_id"], ["user.id"], name="friend_friend_id_fkey"
        ),
        sa.PrimaryKeyConstraint("user_id", name="friend_pkey"),
    )
    # ### end Alembic commands ###
